services:
  mkcert:
    image: vishnunair/docker-mkcert
    container_name: mkcert
    hostname: mkcert
    restart: unless-stopped
    environment:
      - domain=${MKCERT_DOMAINS}
    networks:
      traefik:
        ipv4_address: ${MKCERT_IP4} # Static IP
    labels:
      #  Traefik
      - traefik.enable=false
    volumes:
      - ./certs/:/root/.local/share/mkcert
