http:
  routers:
    dozzle:
      entryPoints:
      - https
      rule: "Host(`dozzle.${SERVER_NAME}.${TOP_LEVEL_DOMAIN}`)"
      middlewares:
      - secured
      tls:
        domains:
        - main: "${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
          sans:
          - "*.${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
      service: dozzle-docker@docker

  services:
    dozzleService:
      loadBalancer:
        servers:
          url: http://dozzle:80
          port: 80
