http:
  routers:
    dozzle:
      entryPoints:
      - https
      rule: "Host(`dozzle.ottoinfo.com`)"
      middlewares:
      - secured
      tls:
        domains:
        - main: "ottoinfo.com"
          sans:
          - "*.ottoinfo.com"
      service: dozzle-nerds-gummy-clusters@docker

  services:
    dozzleService:
      loadBalancer:
        servers:
          url: http://dozzle:80
          port: 80
