http:
  routers:
    dozzle:
      entryPoints:
      - https
      rule: "Host(`dozzle.ottoinfo.local`)"
      middlewares:
      - secured
      tls:
        domains:
        - main: "ottoinfo.local"
          sans:
          - "*.ottoinfo.local"
      service: dozzle-docker@docker

  services:
    dozzleService:
      loadBalancer:
        servers:
          url: http://dozzle:80
          port: 80
