http:
  routers:
    api:
      entryPoints:
      - https
      observability:
        tracing: true
      middlewares:
      - error-pages
      # use as "fallback" for any NON-registered services (with priority below normal)
      rule: HostRegexp(`\.+`)
      priority: 10
      tls:
        domains:
        - main: "${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
          sans:
          - "*.${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
      service: error-docker@docker
