http:
  routers:
    it-tools:
      entryPoints:
      - https
      rule: "Host(`obsidian.ottoinfo.com`)"
      middlewares:
      - secured
      tls:
        certresolver: cloudflare
        domains:
        - main: "ottoinfo.com"
          sans:
          - "*.ottoinfo.com"
      service: obsidian-nerds-gummy-clusters@docker
