# http:
#   routers:
#     portainer:
#       entryPoints:
#       - https
#       rule: "Host(`portainer.${SERVER_NAME}.${TOP_LEVEL_DOMAIN}`)"
#       middlewares:
#       - secured
#       tls:
#         domains:
#         - main: "${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
#           sans:
#           - "*.${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
#       service: portainer-docker@docker
