http:
  routers:
    portainer:
      entryPoints:
      - https
      rule: "Host(`portainer.ottoinfo.com`)"
      middlewares:
      - secured
      tls:
        certresolver: cloudflare
        domains:
        - main: "ottoinfo.com"
          sans:
          - "*.ottoinfo.com"
      service: portainer-nerds-gummy-clusters@docker
