http:
  routers:
    postgres:
      entryPoints:
      - https
      rule: "Host(`postgres.ottoinfo.com`)"
      middlewares:
      - secured
      observability:
        tracing: true
      tls:
        domains:
        - main: "ottoinfo.com"
          sans:
          - "*.ottoinfo.com"
      service: db-nerds-gummy-clusters@docker
