tls:
  certificates:
    - certFile: "/var/traefik/certs/ottoinfo.local.crt"
      keyFile: "/var/traefik/certs/ottoinfo.local.key"
      stores:
        - default
    # Note that since no store is defined,
    # the certificate below will be stored in the `default` store.
