tls:
  certificates:
    certFile: "/etc/certs/ottoinfo.local.crt"
    keyFile: "/etc/certs/ottoinfo.local.key"
  stores:
    default:
      defaultCertificate:
      - certFile: "/etc/certs/ottoinfo.local.crt"
        keyFile: "/etc/certs/ottoinfo.local.key"
