http:
  routers:
    it-tools:
      entryPoints:
      - https
      rule: "Host(`it-tools.ottoinfo.com`)"
      middlewares:
      - secured
      tls:
        domains:
        - main: "ottoinfo.com"
          sans:
          - "*.ottoinfo.com"
      service: it-tools-nerds-gummy-clusters@docker
