http:
  routers:
    api:
      entryPoints:
      - https
      rule: "Host(`${SERVER_NAME}.${TOP_LEVEL_DOMAIN}`)"
      observability:
        tracing: true
      middlewares:
      - secured
      tls:
        domains:
        - main: "${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
          sans:
          - "*.${SERVER_NAME}.${TOP_LEVEL_DOMAIN}"
      service: ui-docker@docker
