http:
  routers:
    api:
      entryPoints:
      - http
      rule: "Host(`ottoinfo.com`)"
      observability:
        tracing: true
      tls:
        certresolver: cloudflare
        domains:
        - main: "ottoinfo.com"
          sans:
          - "*.ottoinfo.com"
      service: ui-nerds-gummy-clusters@docker
